/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchismvc.View;

import com.mycompany.parchismvc.Controller.Controlador;
import com.mycompany.parchismvc.Model.ColorJugador;
import com.mycompany.parchismvc.Model.Jugador;
import com.mycompany.parchismvc.Model.Sala;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import java.util.Map;
import javax.swing.SwingUtilities;

/**
 *
 * @author galle
 */
public class Juego extends javax.swing.JFrame implements GameEvents {
    
    private Controlador controlador;
    private UUID miId;
    private final Map<UUID, ColorJugador> mapaColoresJugadores = new HashMap<>();

    /**
     * Creates new form Juego
     */
    public Juego(Controlador controlador, UUID miId) {
        this.controlador = controlador;
        this.miId = miId;
        initComponents();
        wireEvents();
        // Centra la ventana en la pantalla
        setLocationRelativeTo(null);
        
        // Ocultar etiquetas de jugador inicialmente
        lblJugadorRojo.setText("");
        lblJugadorAzul.setText("");
        lblJugadorVerde.setText("");
        lblJugadorAmarillo.setText("");
        btnTirarDado.setEnabled(false); // Desactivar el botón de tirar al inicio
        
        if (this.controlador != null) {
            this.controlador.setEvents(this);
            ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).setControlador(this.controlador);
        }
    }
    
    /**
     * Genera el texto HTML con avatar e icono para mostrar en las etiquetas de jugador
     */
    private String obtenerTextoConAvatar(Jugador jugador) {
        if (jugador.avatar != null && !jugador.avatar.isEmpty()) {
            // Intenta cargar la imagen del avatar
            try {
                var imgUrl = getClass().getResource(jugador.avatar);
                if (imgUrl != null) {
                    // Retorna HTML con imagen pequeña junto al nombre
                    return "<html><img src='" + imgUrl + "' width='16' height='16'/> " + jugador.nombre + "</html>";
                }
            } catch (Exception ignored) {
                // Si falla, solo retorna el nombre
            }
        }
        return jugador.nombre;
    }
    
    private void wireEvents() {
        btnAbandonar.addActionListener(e -> {
            if (controlador != null) {
                controlador.desconectar();
            }
            this.dispose(); // Cierra la ventana del juego
            System.exit(0); // Asegura que la aplicación se cierre completamente
        });

        btnTirarDado.addActionListener(e -> {
            if (controlador != null) {
                controlador.tirar(miId); // Llamamos al método correcto con el ID del jugador
            }
        });
        
        // Configuramos el listener para cuando se mueva una ficha en el tablero
        ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).setOnMoveListener((indiceFicha, idCasillaDestino) -> {
            if (controlador != null) {
                controlador.mover(miId, indiceFicha);
                // Limpiamos los resaltados inmediatamente después de enviar el movimiento.
                ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).limpiarResaltados();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPTablero = new com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero();
        lblNumeroDado = new javax.swing.JLabel();
        lblNickName = new javax.swing.JLabel();
        btnTirarDado = new javax.swing.JButton();
        btnAbandonar = new javax.swing.JButton();
        lblJugadorRojo = new javax.swing.JLabel();
        lblJugadorVerde = new javax.swing.JLabel();
        lblJugadorAzul = new javax.swing.JLabel();
        lblJugadorAmarillo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1022, 521));

        jPanel1.setBackground(new java.awt.Color(21, 79, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1022, 521));

        javax.swing.GroupLayout JPTableroLayout = new javax.swing.GroupLayout(JPTablero);
        JPTablero.setLayout(JPTableroLayout);
        JPTableroLayout.setHorizontalGroup(
            JPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        JPTableroLayout.setVerticalGroup(
            JPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        lblNumeroDado.setText("jLabel5");

        lblNickName.setText("jLabel6");

        btnTirarDado.setText("Tirar Dado");

        btnAbandonar.setText("Abandonar");

        lblJugadorRojo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJugadorRojo.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadorRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorRojo.setText("ROJO");

        lblJugadorVerde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJugadorVerde.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadorVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorVerde.setText("VERDE");

        lblJugadorAzul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJugadorAzul.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadorAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorAzul.setText("AZUL");

        lblJugadorAmarillo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJugadorAmarillo.setForeground(new java.awt.Color(255, 255, 255));
        lblJugadorAmarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorAmarillo.setText("AMARILLO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJugadorVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(lblJugadorAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnTirarDado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAbandonar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblJugadorRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(lblJugadorAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JPTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumeroDado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNumeroDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorRojo)
                    .addComponent(lblJugadorAzul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorVerde)
                    .addComponent(lblJugadorAmarillo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTirarDado)
                    .addComponent(btnAbandonar))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lblNickName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarJugadores(List<Jugador> jugadores, UUID turnoDe, UUID yo) {
        // Limpiar todas las etiquetas de las bases
        lblJugadorRojo.setText("");
        lblJugadorAzul.setText("");
        lblJugadorVerde.setText("");
        lblJugadorAmarillo.setText("");
        
        lblNickName.setText(""); // Limpiar el nombre del turno anterior
        
        // Asignar nombres y avatares a las etiquetas de color correspondientes
        for (Jugador jugador : jugadores) {
            // Poner el nombre y avatar en la base de su color
            if (jugador.color != null) {
                String textoConAvatar = obtenerTextoConAvatar(jugador);
                switch (jugador.color) {
                    case ROJO -> lblJugadorRojo.setText(textoConAvatar);
                    case AZUL -> lblJugadorAzul.setText(textoConAvatar);
                    case VERDE -> lblJugadorVerde.setText(textoConAvatar);
                    case AMARILLO -> lblJugadorAmarillo.setText(textoConAvatar);
                }
                
                // Guardamos el color del jugador para usarlo después
                if (jugador.id != null && jugador.color != null) {
                    mapaColoresJugadores.put(jugador.id, jugador.color);
                }
            }

            // Si este es el jugador en turno, actualiza lblNickName
            if (turnoDe != null && turnoDe.equals(jugador.id)) {
                lblNickName.setText("Turno de: " + jugador.nombre);
            }
        }

        // Activar el botón de tirar dado solo si es mi turno.
        // Esta lógica debe ir FUERA del bucle para que se evalúe una sola vez.
        if (yo != null && turnoDe != null) {
            btnTirarDado.setEnabled(yo.equals(turnoDe));
        }
    }

    @Override
    public void onConectado(String host, int puerto, String salaId) {
        // No es relevante en esta pantalla
    }

    @Override
    public void onRegistrado(UUID jugadorId) {
        // No es relevante en esta pantalla
    }

    @Override
    public void onEstado(Sala sala, UUID turnoDe, UUID yo) {
        // Este evento actualiza la UI del juego cuando hay cambios
        SwingUtilities.invokeLater(() -> {
            actualizarJugadores(sala.jugadores, turnoDe, this.miId);
            // Sincronizamos el estado visual de las fichas en el tablero.
            ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).actualizarEstadoFichas(sala.fichasPorJugador, this.mapaColoresJugadores, turnoDe, this.miId);
        });
    }

    @Override
    public void onCuentaAtras(int segundos, Sala sala) { }
    @Override
    public void onResultado(boolean ok, String mensaje) { }
    @Override
    public void onDado(UUID jugadorId, int valor) {
        SwingUtilities.invokeLater(() -> {
            String mensaje = "Resultado del dado: " + valor;
            if (valor == 6) {
                mensaje += " (¡Turno extra!)";
            }
            lblNumeroDado.setText(mensaje);

            // Obtenemos el color del jugador que tiró el dado
            ColorJugador colorDelTurno = mapaColoresJugadores.get(jugadorId);

            if (colorDelTurno != null) {
                // Resaltamos las fichas que el jugador puede mover con este dado.
                ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).resaltarFichasMovibles(valor, colorDelTurno);
            }
        });
    }
    @Override
    public void onError(String razon) { }
    
    @Override
    public void onFinPartida(boolean heGanado, UUID ganadorId) {
        SwingUtilities.invokeLater(() -> {
            // Llamar al método del tablero para mostrar la pantalla final
            ((com.mycompany.parchismvc.View.UtilsFront.FondoBGTablero) JPTablero).mostrarPantallaFinal(heGanado);
        });
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego(null, null).setVisible(true); // Para propósitos de testing
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPTablero;
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnTirarDado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJugadorAmarillo;
    private javax.swing.JLabel lblJugadorAzul;
    private javax.swing.JLabel lblJugadorRojo;
    private javax.swing.JLabel lblJugadorVerde;
    private javax.swing.JLabel lblNickName;
    private javax.swing.JLabel lblNumeroDado;
    // End of variables declaration//GEN-END:variables
}
